find_package(LibConfig REQUIRED)

set(LIBCONFIG_TARGET LibConfig::LibConfig)
set(LIBCONFIGPP_TARGET LibConfig::LibConfig++)

if(LIBCONFIG_STATIC_AVAILABLE)
    add_library(${LIBCONFIG_TARGET} STATIC IMPORTED)
    set_target_properties(${LIBCONFIG_TARGET} PROPERTIES IMPORTED_LOCATION ${LIBCONFIG_LIBRARIES})
    target_include_directories(${LIBCONFIG_TARGET} INTERFACE ${LIBCONFIG_INCLUDE_DIR})
endif()
if(LIBCONFIGPP_STATIC_AVAILABLE)
    add_library(${LIBCONFIGPP_TARGET} STATIC IMPORTED)
    set_target_properties(${LIBCONFIGPP_TARGET} PROPERTIES IMPORTED_LOCATION ${LIBCONFIGPP_LIBRARIES})
    target_link_libraries(${LIBCONFIGPP_TARGET} INTERFACE ${LIBCONFIG_TARGET})
    target_include_directories(${LIBCONFIGPP_TARGET} INTERFACE ${LIBCONFIGPP_INCLUDE_DIR})
endif()

unset(LIBCONFIG_TARGET)
unset(LIBCONFIGPP_TARGET)
